version: '3.7'

services:
  spyserver:
    restart: unless-stopped
    privileged: true
    environment:
      - LIST_IN_DIRECTORY=0
      - DEVICE_TYPE=Auto
      - DEVICE_SERIAL=0
      - BIND_PORT=5555
      - AlLOW_CONTROL=1
    ports:
      - "5555:5555"
    image: lloydpick/spyserver:latest
    devices:
      - "/dev/bus/usb"
    cap_add:
      - SYS_NICE
